### ISSUE TITLE
brew upgrade fails because of sha1 deprecation

### ISSUE THREAD

**Issue by ghost** [rnaveiras/homebrew-sphinx#1]
Trace: 
```
brew upgrade
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/rnaveiras/homebrew-sphinx/sphinx.rb:6:in `<class:Sphinx>'
Please report this to the rnaveiras/sphinx tap!
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:85:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:93:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/sha1.rb:3:in `sha1'
/usr/local/Homebrew/Library/Taps/rnaveiras/homebrew-sphinx/sphinx.rb:6:in `<class:Sphinx>'
/usr/local/Homebrew/Library/Taps/rnaveiras/homebrew-sphinx/sphinx.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:201:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:241:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:272:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1368:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1366:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1366:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:37:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

Looks like we need to upgrade formula to sha256.

**Comment by rnaveiras** [comment]
Fixed by #2
